### ISSUE TITLE
Setup logging properly

### ISSUE THREAD

**Issue by pmav99** [PhenoloBoy/FenicePhenolo#3]
`logging.basicConfig` is meant to be used for throw-away scripts. Real applications should set up logging properly. Unfortunately, setting up logging can be harder than you would expect. 

What I suggest is to go through this [tutorial](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial) (feel free to skim through the parts that you already know, but pay attention in the logging configuration part).

As soon as you do, clone [this repo](https://github.com/pmav99/python-logging-example) and play with it. After you are confident that you understand how to log to file and to console, update phenolo in order to define log config from a file.

**Comment by PhenoloBoy** [comment]
Unfortunately, as MRock, is saying:

> Generally Dask does not move logs around. Instead, it is common that whatever mechanism you used to launch Dask handles this.

to get the logs from the workers is a little bit tricky. Not saying that's impossible but I would have to implement a workaround to retransmit to the client the log from the worker.

**Comment by PhenoloBoy** [comment]
> `logging.basicConfig` is meant to be used for throw-away scripts. Real applications should set up logging properly. Unfortunately, setting up logging can be harder than you would expect.

Unfortunately, I don't fully understand what are you trying to point to. In phenolo, there is already a logging system that takes into account the source, the level of the error etc etc.. 
Would be useful if you could point to something that's not properly done. 
Indeed something that must be revisited is the exception management that right now is quite ... "weak"
